from coldfront.config.env import ENV


STORAGE_PLUGIN_STORAGE_UNITS= ENV.str("STORAGE_PLUGIN_STORAGE_UNITS", default="TB")
QUOTA_ATTRIBUTE_NAME= ENV.str("QUOTA_ATTRIBUTE_NAME", default="Storage Quota (TB)")
QUOTA_ID_ATTRIBUTE_NAME = ENV.str("QUOTA_ID_ATTRIBUTE_NAME", default="quota_id")
QUOTA_REPORT_DATE_ATTRIBUTE_NAME= ENV.str("QUOTA_REPORT_DATE_ATTRIBUTE_NAME", default="quota_report_date")
QUOTA_DISPLAY_ATTRIBUTE_NAME= ENV.str("QUOTA_DISPLAY_ATTRIBUTE_NAME", default="quota_display")
USAGE_IN_BYTES_ATTRIBUTE_NAME= ENV.str("USAGE_IN_BYTES_ATTRIBUTE_NAME", default="usage_in_bytes")
USAGE_REPORT_DATE_ATTRIBUTE_NAME= ENV.str("USAGE_REPORT_DATE_ATTRIBUTE_NAME", default="usage_report_date")
# Starfish-specific constants
STORAGE_PLUGIN_STARFISH_VOL_PATH_ATTRIBUTE_NAME = ENV.str("STORAGE_PLUGIN_STARFISH_VOL_PATH_ATTRIBUTE_NAME", default="sf_vol_path")
STARFISH_HOST = ENV.str("STARFISH_HOST")
STARFISH_TOKEN = ENV.str("STARFISH_TOKEN")